---
title: "Notes and resources by topic"
---
<font size = 4>

*(in progress)*

The following index of notes is meant as a helpful reference guide. Nearly all materials were taken from another resource, which is given at the top of each page. If you own these resources and don't wish for us to share the notes we've taken on them, please let us know and we will quickly remove them!



### Notes

- Principles of frequentist statistics
- Data wrangling
    - [Notes P1: Subsets, new columns, summary variables](wrangling.html)
    - [Notes P2: Tidy data, splitting and pivoting columns](tidying.html) - Warning: See pivot_longer and pivot_wider instead of gather and spread
- Model assumptions
- Graphing with ggplot
- Correlation and correlation matrices
- Comparing means: t-test
- Comparing group means: ANOVA
- Tests of independence: chi-square
- Regression
- Logistic Regression
- [Inferential statistics and plotting for regression models](inferential_stats.html)



### Exercises

- [Regression review with Tidy Tuesday coffee data](https://github.com/kyla-mcconnell/stats_group_resources/blob/master/Regression_TidyTues_Coffee.Rmd)
  - [SOLUTION](regression_solution.html)

</font>



<font size=2>





*Sources*

Boehmke, B., & Greenwell, B. M. (2019). Hands-on machine learning with R. CRC Press.

Field, A., Miles, J., & Field, Z. (2012). Discovering statistics using R. Los Angeles, London, New Delhi, Singapore, Washington, DC: Sage.

Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-positive psychology: Undisclosed flexibility in data collection and analysis allows presenting anything as significant. Psychological Science, 22(11), 1359–1366.
https://doi.org/10.1177/0956797611417632

Leek, J. T., & Peng, R. D. (2015). Statistics: P values are just the tip of the iceberg. Nature, 520(7549), 612. https://doi.org/10.1038/520612a

Levshina, N. (2015). How to do linguistics with R: Data exploration and statistical analysis. John Benjamins Publishing Company.

Winter, B. (2013). Linear models and linear mixed effects models in R with linguistic applications. Retrieved from http://arxiv.org/pdf/1308.5499 

Winter, B. (2019). Statistics for linguists: An introduction using R. Routledge.

</font>